name:                acknowledgements
version:             0.1.0.1
github:              "plfa/acknowledgements"
license:             LGPL
author:              "Wen Kokke"
maintainer:          "wen.kokke@gmail.com"
copyright:           "Copyright (C) 2018 Wen Kokke"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/plfa/acknowledgements#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- exceptions
- github
- text
- vector
- yaml >= 0.8.3

executables:
  acknowledgements:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
